#!/usr/bin/env bash -o errexit
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
cd "$ROOT_DIR"


# tests pass?
scripts/test

# build release
scripts/clean
scripts/build

# release
scripts/dist
