#!/usr/bin/env bash -o errexit
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
cd "$ROOT_DIR"


# uninstall
pip uninstall --yes requests-walmart-auth

# clean artifacts
rm -rf *.egg-info
